/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT dsk_app2.cdb */

#define CHIP_5510PG2_2 1

/*  Include Header Files  */
#include <std.h>
#include <prd.h>
#include <hst.h>
#include <swi.h>
#include <log.h>
#include <sts.h>
#include <csl_dma.h>
#include <csl_emif.h>
#include <csl_mcbsp.h>

#ifdef __cplusplus
extern "C" {
#endif

extern PRD_Obj PRD_blinkLED;
extern PRD_Obj PRD_load;
extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj PRD_swi;
extern SWI_Obj processBufferSwi;
extern LOG_Obj LOG_system;
extern LOG_Obj logTrace;
extern STS_Obj IDL_busyObj;
extern DMA_Config dmaCfgReceive;
extern DMA_Config dmaCfgTransmit;
extern EMIF_Config emifCfg0;
extern MCBSP_Config mcbspCfg1;
extern MCBSP_Config mcbspCfg2;
extern DMA_Handle hDmaXmt;
extern DMA_Handle hDmaRcv;
extern MCBSP_Handle C55XX_CONTROLHANDLE_hMcbsp;
extern MCBSP_Handle C55XX_DMA_MCBSP_hMcbsp;
extern void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
