/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT dsk_app2.cdb */

/*  Include Header File  */
#include "dsk_app2cfg.h"


#pragma CODE_SECTION(CSL_cfgInit,".text:CSL_cfgInit")

extern Uint16 gBufferRcvPingL;

extern Uint16 gBufferXmtPingL;

/*  Config Structures */
DMA_Config dmaCfgReceive = {
    0x020d,        /*  Source Destination Register (CSDP)  */
    0xcb49,        /*  Control Register (CCR)  */
    0x0020,        /*  Interrupt Control Register (CICR)  */
    (DMA_AdrPtr)0x6002,        /*  Lower Source Address (CSSA_L)- Numeric(Byte Address)  */
    0x0000,        /*  Upper Source Address (CSSA_U) - Numeric(Byte Address)  */
    (DMA_AdrPtr)&gBufferRcvPingL,        /*  Lower Destination Address (CDSA_L) - Symbolic(Byte Address)  */
    NULL,        /*  Upper Destination Address (CDSA_U) - Symbolic(Byte Address)  */
    0x0002,        /*  Element Number (CEN)  */
    0x0400,        /*  Frame Number (CFN)  */
    0x0000,        /*  Frame Index (CFI)  */
    0x0000         /*  Element Index (CEI)  */
};

DMA_Config dmaCfgTransmit = {
    0x0605,        /*  Source Destination Register (CSDP)  */
    0x3b4a,        /*  Control Register (CCR)  */
    0x0020,        /*  Interrupt Control Register (CICR)  */
    (DMA_AdrPtr)&gBufferXmtPingL,        /*  Lower Source Address (CSSA_L) - Symbolic(Byte Address)  */
    NULL,        /*  Upper Source Address (CSSA_U) - Symbolic(Byte Address)  */
    (DMA_AdrPtr)0x6006,        /*  Lower Destination Address (CDSA_L)- Numeric(Byte Address)  */
    0x0000,        /*  Upper Destination Address (CDSA_U) - Numeric(Byte Address)  */
    0x0002,        /*  Element Number (CEN)  */
    0x0400,        /*  Frame Number (CFN)  */
    0x0000,        /*  Frame Index (CFI)  */
    0x0000         /*  Element Index (CEI)  */
};

EMIF_Config emifCfg0 = {
    0x0221,        /*  Global Control Register   */
    0xffff,        /*  Global Reset Register   */
    0x3fff,        /*  CE0 Space Control Register 1   */
    0x5fff,        /*  CE0 Space Control Register 2   */
    0x0000,        /*  CE0 Space Control Register 3   */
    0x1038,        /*  CE1 Space Control Register 1   */
    0x0038,        /*  CE1 Space Control Register 2   */
    0x0000,        /*  CE1 Space Control Register 3   */
    0x1050,        /*  CE2 Space Control Register 1   */
    0x0050,        /*  CE2 Space Control Register 2   */
    0x0000,        /*  CE2 Space Control Register 3   */
    0x1050,        /*  CE3 Space Control Register 1   */
    0x0050,        /*  CE3 Space Control Register 2   */
    0x0000,        /*  CE3 Space Control Register 3   */
    0x2b11,        /*  SDRAM Control Register 1   */
    0x0578,        /*  SDRAM Period Register   */
    0xffff,        /*  SDRAM Initialization Register   */
    0x0535         /*  SDRAM Control Register 2   */
};

MCBSP_Config mcbspCfg1 = {
    0x1000,        /*  Serial Port Control Register 1   */
    0x0100,        /*  Serial Port Control Register 2   */
    0x0000,        /*  Receive Control Register 1   */
    0x0000,        /*  Receive Control Register 2   */
    0x0040,        /*  Transmit Control Register 1   */
    0x0000,        /*  Transmit Control Register 2   */
    0x0063,        /*  Sample Rate Generator Register 1   */
    0x2013,        /*  Sample Rate Generator Register 2   */
    0x0000,        /*  Multichannel Control Register 1   */
    0x0000,        /*  Multichannel Control Register 2   */
    0x1a0a,        /*  Pin Control Register   */
    0x0000,        /*  Receive Channel Enable Register Partition A   */
    0x0000,        /*  Receive Channel Enable Register Partition B   */
    0x0000,        /*  Receive Channel Enable Register Partition C   */
    0x0000,        /*  Receive Channel Enable Register Partition D   */
    0x0000,        /*  Receive Channel Enable Register Partition E   */
    0x0000,        /*  Receive Channel Enable Register Partition F   */
    0x0000,        /*  Receive Channel Enable Register Partition G   */
    0x0000,        /*  Receive Channel Enable Register Partition H   */
    0x0000,        /*  Transmit Channel Enable Register Partition A   */
    0x0000,        /*  Transmit Channel Enable Register Partition B   */
    0x0000,        /*  Transmit Channel Enable Register Partition C   */
    0x0000,        /*  Transmit Channel Enable Register Partition D   */
    0x0000,        /*  Transmit Channel Enable Register Partition E   */
    0x0000,        /*  Transmit Channel Enable Register Partition F   */
    0x0000,        /*  Transmit Channel Enable Register Partition G   */
    0x0000         /*  Transmit Channel Enable Register Partition H   */
};

MCBSP_Config mcbspCfg2 = {
    0x0000,        /*  Serial Port Control Register 1   */
    0x0100,        /*  Serial Port Control Register 2   */
    0x0140,        /*  Receive Control Register 1   */
    0x0000,        /*  Receive Control Register 2   */
    0x0140,        /*  Transmit Control Register 1   */
    0x0000,        /*  Transmit Control Register 2   */
    0x0000,        /*  Sample Rate Generator Register 1   */
    0x0000,        /*  Sample Rate Generator Register 2   */
    0x0000,        /*  Multichannel Control Register 1   */
    0x0000,        /*  Multichannel Control Register 2   */
    0x0003,        /*  Pin Control Register   */
    0x0000,        /*  Receive Channel Enable Register Partition A   */
    0x0000,        /*  Receive Channel Enable Register Partition B   */
    0x0000,        /*  Receive Channel Enable Register Partition C   */
    0x0000,        /*  Receive Channel Enable Register Partition D   */
    0x0000,        /*  Receive Channel Enable Register Partition E   */
    0x0000,        /*  Receive Channel Enable Register Partition F   */
    0x0000,        /*  Receive Channel Enable Register Partition G   */
    0x0000,        /*  Receive Channel Enable Register Partition H   */
    0x0000,        /*  Transmit Channel Enable Register Partition A   */
    0x0000,        /*  Transmit Channel Enable Register Partition B   */
    0x0000,        /*  Transmit Channel Enable Register Partition C   */
    0x0000,        /*  Transmit Channel Enable Register Partition D   */
    0x0000,        /*  Transmit Channel Enable Register Partition E   */
    0x0000,        /*  Transmit Channel Enable Register Partition F   */
    0x0000,        /*  Transmit Channel Enable Register Partition G   */
    0x0000         /*  Transmit Channel Enable Register Partition H   */
};

/*  Handles  */
DMA_Handle hDmaXmt;
DMA_Handle hDmaRcv;
MCBSP_Handle C55XX_CONTROLHANDLE_hMcbsp;
MCBSP_Handle C55XX_DMA_MCBSP_hMcbsp;

/*
 *  ======== CSL_cfgInit() ========  
 */
void CSL_cfgInit()
{
    dmaCfgReceive.dmacdsal = (DMA_AdrPtr)(((Uint32)(&gBufferRcvPingL) << 1) & 0xFFFF);
    dmaCfgReceive.dmacdsau = (Uint16)((Uint32)(&gBufferRcvPingL) >> 15);
    dmaCfgTransmit.dmacssal = (DMA_AdrPtr)(((Uint32)(&gBufferXmtPingL) << 1) & 0xFFFF);
    dmaCfgTransmit.dmacssau = (Uint16)((Uint32)(&gBufferXmtPingL) >> 15);
    hDmaXmt = DMA_open(DMA_CHA0, DMA_OPEN_RESET);
    hDmaRcv = DMA_open(DMA_CHA1, DMA_OPEN_RESET);
    C55XX_CONTROLHANDLE_hMcbsp = MCBSP_open(MCBSP_PORT1, MCBSP_OPEN_RESET);
    C55XX_DMA_MCBSP_hMcbsp = MCBSP_open(MCBSP_PORT2, MCBSP_OPEN_RESET);
        
    DMA_config(hDmaXmt, &dmaCfgTransmit);
    DMA_config(hDmaRcv, &dmaCfgReceive);
    EMIF_config(&emifCfg0);
    MCBSP_config(C55XX_CONTROLHANDLE_hMcbsp, &mcbspCfg1);
    MCBSP_config(C55XX_DMA_MCBSP_hMcbsp, &mcbspCfg2);

    /* You must use DMA_start() in your main code to start the DMA. */

	
    
    /* You must use MCBSP_start() in your main code to start the MCBSP. */

    
    

}
